name: CSV Lint workflow

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    name: csv lint
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas frictionless
    - name: Validate individual CSVs
      run: frictionless validate $GITHUB_WORKSPACE/data/**/*.csv
    - name: Validate schema of main breweries.csv
      run: frictionless validate $GITHUB_WORKSPACE/breweries.resource.json
